tap "github/bootstrap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "caskroom/fonts"
tap "homebrew/formula-analytics"
tap "homebrew/services"
tap "homebrew/test-bot"
brew "antigen"
brew "azure-cli"
cask "balenaetcher"
brew "docker", link: false
brew "docker-machine", link: false
brew "exa"
brew "fd"
brew "fork-cleaner"
brew "git"
brew "go"
brew "glide"
brew "gnupg"
brew "grc"
brew "hub"
brew "imagemagick"
brew "jq"
brew "mas"
brew "pidof"
brew "rbenv"
brew "readline"
brew "shellcheck"
brew "ssh-copy-id"
brew "wget"
cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "arduino"
cask "docker"
cask "drawio"
cask "fastlane"
cask "firefox"
cask "font-fira-code"
cask "fork"
cask "fritzing"
cask "google-chrome"
cask "hazel"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keycastr"
cask "microsoft-office"
cask "nvalt"
cask "obs"
cask "postman"
cask "sizeup"
cask "tripmode"
cask "visual-studio-code"
cask "vmware-horizon-client"
cask "webex-teams"
mas "1Password 7", id: 1333542190
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Microsoft Remote Desktop", id: 1295203466
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
