#!/bin/bash

# clears the dock of all apps, then adds your individual dock config
# config file:
# ~/Library/Preferences/com.apple.dock.plist

# for readability and ease of use
DEF_W="/usr/bin/defaults write"
PLB=/usr/libexec/PlistBuddy
OSA=/usr/bin/osascript

DOCK="com.apple.dock"

# rein in some wooly XML
APP_HEAD="<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>"
APP_TAIL="</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
FOLDER_HEAD="<dict><key>tile-data</key><dict><key>arrangement</key><integer>0</integer><key>displayas</key><integer>1</integer><key>file-data</key><dict><key>_CFURLString</key><string>"
FOLDER_TAIL="</string><key>_CFURLStringType</key><integer>0</integer></dict><key>preferreditemsize</key><integer>-1</integer><key>showas</key><integer>3</integer></dict><key>tile-type</key><string>directory-tile</string></dict>"

function set_dock_apps () {

    $DEF_W $DOCK 'checked-for-launchpad' -bool true
  
    # clear the dock of existing apps
    $DEF_W $DOCK 'persistent-apps' -array ''
    $DEF_W $DOCK 'persistent-others' -array ''
 
    SAVEIFS=$IFS
    IFS=$(echo -en "\n\b")
    for APP in $(cat $(dirname $0)/../dock-apps-to-add)
      do
        IFS=$SAVEIFS
        echo $APP
        # dloc=$(defaults read com.apple.dock persistent-apps | grep file-label | awk '/'$APP'/  {printf NR}')
        # dloc=$[$dloc-1]
        # echo $dloc
        # sudo -u $USER /usr/libexec/PlistBuddy -c "Delete persistent-apps:$dloc" ~/Library/Preferences/com.apple.dock.plist
        if [ "$APP" = "SPACER" ]; then
          $DEF_W $DOCK 'persistent-apps' -array-add '{ tile-data = {}; tile-type = "spacer-tile"; }'
        else
          $DEF_W $DOCK 'persistent-apps' \
          -array-add "$APP_HEAD/Applications/$APP/$APP_TAIL"
        fi

    done
    IFS=$SAVEIFS

  $DEF_W $DOCK 'persistent-others' -array-add "$FOLDER_HEAD$HOME/Downloads$FOLDER_TAIL"  
  $OSA -e 'tell application "System Events" to set the autohide of the dock preferences to true'
  $OSA -e 'tell application "Dock" to quit'
  
}


# Set the icon size of Dock items to 36 pixels
DEF_W $DOCK tilesize -int 36

# Minimize windows into their application’s icon
DEF_W $DOCK minimize-to-application -bool true

#Move dock to left edge of screen
DEF_W $DOCK orientation -string left

set_dock_apps