#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com steve@bargelt.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get flsexkgtbjbhfcnz42jw5gpewe .ssh/id_rsa
onepassword_get mbo6xq6j75g7tgyhhdfxlee37a .ssh/id_rsa_PERSONAL

echo "Storing SSH keys in keychain..."
ssh-add -K

# if ! [ -f "$HOME/.secrets" ]
# then
#   echo "Extracting secrets..."
#   if ! command -v jq >/dev/null
#   then
#     echo "Install jq first!" >&2
#     exit 1
#   fi
#   onepassword_login
#   BINTRAY_KEY=$(op get item t6wkb3pguncltiehjfoeft3r6q | jq -r '.details.sections[1].fields[].v')
#   GITHUB_TOKEN=$(op get item g6klazxi3ffprbnou2mexznlay | jq -r '.details.sections[1].fields[].v')
#   cat > "$HOME/.secrets" <<EOF
# export BINTRAY_KEY=$BINTRAY_KEY
# export GITHUB_TOKEN=$GITHUB_TOKEN
# EOF
#   chmod 600 "$HOME/.secrets"
# fi

# echo "Setting up GPG..."
# if ! command -v gpg >/dev/null
# then
#     echo "Install GPG first!" >&2
#     exit 1
# fi

# chmod 700 ~/.gnupg
# gpg --import ~/.gnupg/mike@mikemcquaid.com.public.gpg-key \
#              ~/.gnupg/mike@mikemcquaid.com.private.gpg-key
