#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/extract-onepassword-secrets
script/install-vscode-extensions

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh
fi

# mkdir ~/code/go
# go get -u github.com/justjanne/powerline-go

# Install Oh My ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install Spaceship Theme for ZSH
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# Call other scripts
script/dockFixup

script/macOS
